name: CI

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Type check
        run: npx tsc --noEmit

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env :
           GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
           MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Run Cypress tests
        run: npx start-server-and-test 'npm run dev' http://localhost:3000 'npx cypress run'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}    
          MONGODB_URI: ${{ secrets.MONGODB_URI }}